const TagOptions = [
  { value: '运动', label: '🏃 运动' },
  { value: '美食', label: '🍔 美食' },
  { value: '学习', label: '📚 学习' },
  { value: '游戏', label: '🎮 游戏' },
  { value: '旅行', label: '✈️ 旅行' },
  { value: '电影', label: '🎬 电影' },
  { value: '音乐', label: '🎵 音乐' },
  { value: '摄影', label: '📷 摄影' },
  { value: '绘画', label: '🎨 绘画' },
  { value: '健身', label: '💪 健身' },
  { value: '编程', label: '💻 编程' },
  { value: '桌游', label: '🎲 桌游' },
  { value: '书籍', label: '📖 书籍' },
  { value: '动漫', label: '🖌️ 动漫' },
  { value: '宠物', label: '🐶 宠物' },
  { value: '烹饪', label: '🍳 烹饪' },
  { value: '夜跑', label: '🌙 夜跑' },
  { value: '露营', label: '🏕️ 露营' },
  { value: '科技', label: '🔬 科技' },
  { value: '创业', label: '🚀 创业' },
  { value: '电音', label: '🎧 电音' },
  { value: '街舞', label: '🕺 街舞' },
  { value: '骑行', label: '🚴 骑行' },
  { value: '篮球', label: '🏀 篮球' },
  { value: '足球', label: '⚽ 足球' },
  { value: '羽毛球', label: '🏸 羽毛球' },
  { value: '乒乓球', label: '🏓 乒乓球' },
  { value: '网球', label: '🎾 网球' },
  { value: '滑板', label: '🛹 滑板' },
  { value: '极限运动', label: '🧗 极限运动' },
  { value: '魔术', label: '🎩 魔术' },
  { value: '无人机', label: '🚁 无人机' },
  { value: '射箭', label: '🏹 射箭' },
  { value: '赛车', label: '🏎️ 赛车' },
  { value: '跑酷', label: '🤸 跑酷' },
  { value: '国风', label: '🀄 国风' },
  { value: '汉服', label: '👘 汉服' },
  { value: '手工艺', label: '🧵 手工艺' },
  { value: '乐器', label: '🎻 乐器' },
  { value: 'KTV', label: '🎤 KTV' },
  { value: '桌球', label: '🎱 桌球' },
  { value: '心理学', label: '🧠 心理学' },
  { value: '投资理财', label: '💰 投资理财' },
  { value: '天文', label: '🔭 天文' },
  { value: '冥想', label: '🧘 冥想' },
  { value: '占星', label: '🔮 占星' },
  { value: '社科', label: '🏛️ 社科' },
  { value: '公益', label: '🤝 公益' },
];

export default TagOptions;